package crawler

import (
	"context"
	"sort"
	"strings"
	"sync"

	"github.com/evoscanner/evoscanner/internal/scanner"
)

type DiscoveredPath struct {
	URL        string
	StatusCode int
	Size       int // response body length
}

var commonPaths = []string{
	// ── Admin panels ──
	"/admin",
	"/admin/",
	"/administrator",
	"/administrator/",
	"/admin/login",
	"/admin/dashboard",
	"/admin.php",
	"/admin/index.php",
	"/admin/config",
	"/admin/console",
	"/admin/settings",
	"/admin/users",
	"/admin/logs",
	"/admin/db",
	"/admin/backup",
	"/admin/upload",
	"/admin/api",
	"/admin/panel",
	"/admin/monitor",
	"/admin/system",
	"/admin/manage",
	"/user/admin",
	"/moderator",
	"/manager",
	"/manager/html",
	"/manager/status",
	"/manager/text",
	"/backend",
	"/backend/login",
	"/controlpanel",
	"/cp",
	"/cpanel",
	"/panel",
	"/portal",
	"/sysadmin",
	"/webadmin",
	"/superadmin",
	"/root",
	"/maintenance",
	"/wp-admin",
	"/wp-admin/install.php",
	"/wp-admin/setup-config.php",
	"/wp-login.php",
	"/wp-config.php.bak",
	"/wp-config.php.old",
	"/wp-config.php~",
	"/wp-config.txt",

	// ── API / Documentation ──
	"/api",
	"/api/",
	"/api/v1",
	"/api/v2",
	"/api/v3",
	"/api/v4",
	"/api/health",
	"/api/status",
	"/api/config",
	"/api/internal",
	"/api/auth",
	"/api/auth/login",
	"/api/users",
	"/api/user",
	"/api/me",
	"/api/admin",
	"/api/debug",
	"/api/docs",
	"/api/swagger",
	"/api/graphql",
	"/api/token",
	"/api/token/refresh",
	"/api/upload",
	"/api/files",
	"/api/search",
	"/api/export",
	"/api/import",
	"/api/backup",
	"/api/settings",
	"/api/logs",
	"/api/webhooks",
	"/api/keys",
	"/api/credentials",
	"/api/system",
	"/api/info",
	"/api/version",
	"/api/ping",
	"/graphql",
	"/graphql/console",
	"/graphiql",
	"/playground",
	"/altair",
	"/swagger",
	"/swagger/",
	"/swagger-ui",
	"/swagger-ui/",
	"/swagger-ui.html",
	"/swagger-resources",
	"/swagger.json",
	"/swagger.yaml",
	"/openapi.json",
	"/openapi.yaml",
	"/api-docs",
	"/api-docs/",
	"/redoc",
	"/rest",
	"/rest/api",
	"/v1",
	"/v2",
	"/v3",
	"/wsdl",
	"/soap",
	"/services",
	"/service",

	// ── Source control / CI leaks ──
	"/.git/",
	"/.git/config",
	"/.git/HEAD",
	"/.git/index",
	"/.git/logs/HEAD",
	"/.git/packed-refs",
	"/.git/refs/heads/master",
	"/.git/refs/heads/main",
	"/.git/COMMIT_EDITMSG",
	"/.git/description",
	"/.git/objects/",
	"/.gitignore",
	"/.gitattributes",
	"/.svn/",
	"/.svn/entries",
	"/.svn/wc.db",
	"/.hg/",
	"/.hg/store",
	"/.hg/hgrc",
	"/.bzr/README",
	"/.cvs",
	"/.gitlab-ci.yml",
	"/.github/",
	"/.github/workflows",
	"/.circleci/config.yml",
	"/.travis.yml",
	"/Jenkinsfile",
	"/Dockerfile",
	"/docker-compose.yml",
	"/docker-compose.yaml",
	"/docker-compose.override.yml",
	"/.dockerignore",
	"/Makefile",
	"/Vagrantfile",
	"/Procfile",
	"/Rakefile",
	"/Gruntfile.js",
	"/gulpfile.js",
	"/webpack.config.js",
	"/tsconfig.json",
	"/babel.config.js",
	"/.babelrc",
	"/.eslintrc",
	"/.eslintrc.json",
	"/.prettierrc",
	"/sonar-project.properties",

	// ── Config / Secrets exposure ──
	"/.env",
	"/.env.bak",
	"/.env.old",
	"/.env.save",
	"/.env.local",
	"/.env.production",
	"/.env.development",
	"/.env.staging",
	"/.env.test",
	"/.env.example",
	"/.env.sample",
	"/.env.dist",
	"/.htaccess",
	"/.htpasswd",
	"/.npmrc",
	"/.yarnrc",
	"/.editorconfig",
	"/web.config",
	"/web.config.bak",
	"/app.config",
	"/appsettings.json",
	"/appsettings.Development.json",
	"/appsettings.Production.json",
	"/config.php",
	"/config.php.bak",
	"/config.php.old",
	"/config.inc.php",
	"/config.yml",
	"/config.yaml",
	"/config.json",
	"/config.xml",
	"/config.ini",
	"/config.bak",
	"/configuration.php",
	"/database.yml",
	"/database.json",
	"/settings.py",
	"/settings.json",
	"/settings.ini",
	"/wp-config.php",
	"/local.xml",
	"/local.json",
	"/package.json",
	"/package-lock.json",
	"/composer.json",
	"/composer.lock",
	"/yarn.lock",
	"/Gemfile",
	"/Gemfile.lock",
	"/requirements.txt",
	"/Pipfile",
	"/Pipfile.lock",
	"/poetry.lock",
	"/go.mod",
	"/go.sum",
	"/pom.xml",
	"/build.gradle",
	"/build.xml",
	"/ivy.xml",
	"/credentials.json",
	"/credentials.xml",
	"/service-account.json",
	"/firebase.json",
	"/firebaserc",
	"/id_rsa",
	"/id_rsa.pub",
	"/id_ed25519",
	"/.ssh/authorized_keys",
	"/keystore.jks",
	"/truststore.jks",
	"/.aws/credentials",
	"/.aws/config",
	"/secrets.json",
	"/secrets.yml",
	"/secret.key",
	"/master.key",
	"/private.key",
	"/server.key",
	"/server.crt",
	"/ssl.key",

	// ── Backup / Archive ──
	"/backup",
	"/backup/",
	"/backup.zip",
	"/backup.tar.gz",
	"/backup.tar",
	"/backup.sql",
	"/backup.sql.gz",
	"/backup.sql.bz2",
	"/backup.rar",
	"/backup.7z",
	"/site.zip",
	"/site.tar.gz",
	"/site.tar",
	"/www.zip",
	"/www.tar.gz",
	"/web.zip",
	"/web.tar.gz",
	"/old.zip",
	"/old.tar.gz",
	"/db.sql",
	"/db.sql.gz",
	"/db.tar.gz",
	"/database.sql",
	"/database.sql.gz",
	"/dump.sql",
	"/dump.sql.gz",
	"/data.sql",
	"/data.zip",
	"/export.sql",
	"/export.zip",
	"/export.csv",
	"/.backup",
	"/archive",
	"/archive/",
	"/archive.zip",
	"/archive.tar.gz",
	"/bak",
	"/bak/",
	"/old",
	"/old/",
	"/save",
	"/snapshot",
	"/migration",

	// ── Database management ──
	"/phpmyadmin",
	"/phpmyadmin/",
	"/pma",
	"/pma/",
	"/adminer",
	"/adminer.php",
	"/dbadmin",
	"/mysql",
	"/mysqladmin",
	"/pgadmin",
	"/pgadmin4",
	"/redis",
	"/redis/info",
	"/mongo",
	"/mongodb",
	"/mongo-express",
	"/elasticsearch",
	"/elasticsearch/",
	"/_cat/indices",
	"/_cat/health",
	"/_cluster/health",
	"/_cluster/settings",
	"/_nodes",
	"/_nodes/stats",
	"/_search",
	"/_all",
	"/_mapping",
	"/solr",
	"/solr/",
	"/solr/admin",
	"/solr/admin/cores",
	"/couchdb",
	"/couchdb/",
	"/_utils",
	"/_all_dbs",
	"/neo4j",
	"/memcached",
	"/rabbitmq",
	"/influxdb",

	// ── Application frameworks ──
	"/wp-content/",
	"/wp-content/uploads/",
	"/wp-content/debug.log",
	"/wp-content/plugins/",
	"/wp-content/themes/",
	"/wp-includes/",
	"/wp-json",
	"/wp-json/wp/v2/users",
	"/wp-json/wp/v2/posts",
	"/wp-json/wp/v2/pages",
	"/xmlrpc.php",
	"/wp-cron.php",
	"/wp-trackback.php",
	"/readme.html",
	"/license.txt",
	"/jmx-console",
	"/jmx-console/",
	"/web-console",
	"/web-console/",
	"/invoker/JMXInvokerServlet",
	"/invoker/EJBInvokerServlet",
	"/status?full=true",
	"/console",
	"/console/",
	"/console/login",
	"/h2-console",
	"/h2-console/",
	"/actuator",
	"/actuator/",
	"/actuator/health",
	"/actuator/env",
	"/actuator/info",
	"/actuator/beans",
	"/actuator/mappings",
	"/actuator/configprops",
	"/actuator/heapdump",
	"/actuator/threaddump",
	"/actuator/loggers",
	"/actuator/logfile",
	"/actuator/metrics",
	"/actuator/prometheus",
	"/actuator/jolokia",
	"/actuator/trace",
	"/actuator/httptrace",
	"/actuator/auditevents",
	"/actuator/scheduledtasks",
	"/actuator/caches",
	"/actuator/conditions",
	"/actuator/flyway",
	"/actuator/liquibase",
	"/actuator/sessions",
	"/actuator/shutdown",
	"/jolokia",
	"/jolokia/list",
	"/jolokia/read",
	"/jolokia/version",
	"/elmah.axd",
	"/trace.axd",
	"/glimpse.axd",

	// ── Debug / Development ──
	"/debug",
	"/debug/",
	"/debug/pprof",
	"/debug/pprof/cmdline",
	"/debug/pprof/profile",
	"/debug/pprof/trace",
	"/debug/pprof/goroutine",
	"/debug/pprof/heap",
	"/debug/vars",
	"/debug/default/view",
	"/debug/requests",
	"/_debugbar",
	"/_debugbar/open",
	"/_profiler",
	"/_profiler/phpinfo",
	"/profiler",
	"/telescope",
	"/telescope/requests",
	"/telescope/exceptions",
	"/telescope/logs",
	"/telescope/dumps",
	"/telescope/queries",
	"/horizon",
	"/horizon/api",
	"/horizon/dashboard",
	"/nova",
	"/nova/login",
	"/silk/",
	"/djdt/",
	"/__debug__/",
	"/devtools",
	"/dev",
	"/dev/",
	"/test",
	"/test/",
	"/testing",
	"/staging",
	"/demo",
	"/demo/",
	"/sandbox",
	"/trace",
	"/phpinfo.php",
	"/php_info.php",
	"/info.php",
	"/info",
	"/pi.php",
	"/test.php",
	"/t.php",
	"/server-status",
	"/server-info",
	"/apc.php",
	"/opcache",
	"/opcache-status",
	"/xdebug",
	"/clockwork",
	"/ray",
	"/laravel-debugbar",

	// ── Auth / User pages ──
	"/login",
	"/login/",
	"/signin",
	"/sign-in",
	"/auth",
	"/auth/",
	"/auth/login",
	"/auth/register",
	"/auth/callback",
	"/auth/forgot",
	"/auth/reset",
	"/oauth",
	"/oauth/authorize",
	"/oauth/token",
	"/oauth2/authorize",
	"/oauth2/token",
	"/connect/authorize",
	"/connect/token",
	"/token",
	"/jwt",
	"/sso",
	"/sso/login",
	"/cas/login",
	"/saml",
	"/saml/metadata",
	"/saml/login",
	"/adfs/ls",
	"/signup",
	"/sign-up",
	"/register",
	"/registration",
	"/forgot-password",
	"/reset-password",
	"/change-password",
	"/password/reset",
	"/password/email",
	"/logout",
	"/signout",
	"/session",
	"/sessions",
	"/account",
	"/accounts",
	"/dashboard",
	"/dashboard/",
	"/profile",
	"/user",
	"/users",
	"/member",
	"/members",
	"/my-account",
	"/mypage",
	"/me",
	"/self",
	"/preferences",

	// ── File upload / storage ──
	"/upload",
	"/upload/",
	"/uploads",
	"/uploads/",
	"/file",
	"/files",
	"/files/",
	"/documents",
	"/documents/",
	"/attachments",
	"/attachments/",
	"/data",
	"/data/",
	"/images",
	"/images/",
	"/img",
	"/img/",
	"/photos",
	"/videos",
	"/static",
	"/static/",
	"/assets",
	"/assets/",
	"/media",
	"/media/",
	"/public",
	"/public/",
	"/resources",
	"/resources/",
	"/content",
	"/content/",
	"/cdn",
	"/storage",
	"/storage/",
	"/storage/logs",
	"/storage/app",
	"/storage/framework",
	"/var/log",
	"/logs",
	"/logs/",
	"/log",
	"/log/",
	"/error.log",
	"/errors.log",
	"/access.log",
	"/debug.log",
	"/app.log",
	"/application.log",
	"/system.log",
	"/server.log",
	"/catalina.out",
	"/laravel.log",

	// ── Temp / Misc ──
	"/tmp",
	"/tmp/",
	"/temp",
	"/temp/",
	"/cache",
	"/cache/",
	"/cgi-bin/",
	"/bin",
	"/bin/",
	"/include",
	"/includes",
	"/inc",
	"/lib",
	"/lib/",
	"/src",
	"/src/",
	"/app",
	"/app/",
	"/internal",
	"/private",
	"/private/",
	"/secret",
	"/hidden",
	"/restricted",
	"/confidential",
	"/secure",
	"/protected",
	"/system",
	"/system/",

	// ── Well-known / Standards ──
	"/robots.txt",
	"/sitemap.xml",
	"/sitemap_index.xml",
	"/sitemaps.xml",
	"/sitemap1.xml",
	"/sitemap2.xml",
	"/crossdomain.xml",
	"/clientaccesspolicy.xml",
	"/security.txt",
	"/.well-known/security.txt",
	"/.well-known/openid-configuration",
	"/.well-known/jwks.json",
	"/.well-known/change-password",
	"/.well-known/apple-app-site-association",
	"/.well-known/assetlinks.json",
	"/.well-known/nodeinfo",
	"/.well-known/webfinger",
	"/favicon.ico",
	"/humans.txt",
	"/ads.txt",
	"/app-ads.txt",
	"/manifest.json",
	"/site.webmanifest",
	"/browserconfig.xml",

	// ── Monitoring / Health ──
	"/status",
	"/status/",
	"/health",
	"/health/",
	"/healthz",
	"/healthcheck",
	"/readyz",
	"/livez",
	"/startupz",
	"/metrics",
	"/metrics/",
	"/monitoring",
	"/monitoring/",
	"/prometheus",
	"/prometheus/",
	"/grafana",
	"/grafana/",
	"/kibana",
	"/kibana/",
	"/nagios",
	"/zabbix",
	"/munin",
	"/cacti",
	"/datadog",
	"/newrelic",
	"/apm",
	"/statsd",

	// ── WEB-INF / Java ──
	"/WEB-INF/web.xml",
	"/WEB-INF/classes/",
	"/WEB-INF/lib/",
	"/WEB-INF/config/",
	"/WEB-INF/spring/",
	"/WEB-INF/classes/applicationContext.xml",
	"/WEB-INF/classes/hibernate.cfg.xml",
	"/WEB-INF/classes/log4j.properties",
	"/META-INF/",
	"/META-INF/MANIFEST.MF",
	"/META-INF/context.xml",
	"/META-INF/maven/",

	// ── CMS / Known apps ──
	"/drupal",
	"/drupal/",
	"/joomla",
	"/joomla/administrator",
	"/magento",
	"/magento/admin",
	"/shopify",
	"/typo3",
	"/typo3/install",
	"/typo3conf/",
	"/umbraco",
	"/umbraco/login",
	"/sitefinity",
	"/kentico",
	"/sitecore",
	"/sitecore/login",
	"/sitecore/admin",
	"/bitrix",
	"/bitrix/admin",
	"/modx",
	"/modx/manager",
	"/craft/",
	"/craft/admin",
	"/ghost",
	"/ghost/api",
	"/strapi",
	"/strapi/admin",
	"/keystone",
	"/directus",
	"/directus/admin",
	"/contentful",
	"/sanity",
	"/prismic",
	"/netlify",
	"/vercel.json",
	"/next.config.js",
	"/nuxt.config.js",
	"/angular.json",
	"/vue.config.js",

	// ── Mail / Communication ──
	"/mail",
	"/mail/",
	"/webmail",
	"/webmail/",
	"/roundcube",
	"/roundcube/",
	"/squirrelmail",
	"/zimbra",
	"/owa",
	"/owa/",
	"/autodiscover/autodiscover.xml",
	"/Microsoft-Server-ActiveSync",
	"/ecp",
	"/ecp/",
	"/ews",
	"/ews/exchange.asmx",
	"/rpc",

	// ── Error pages (info leak) ──
	"/error",
	"/error/",
	"/errors",
	"/errors/",
	"/404",
	"/500",
	"/403",
	"/401",
	"/502",
	"/503",
	"/error.html",
	"/404.html",
	"/500.html",

	// ── Cloud metadata (SSRF-adjacent) ──
	"/latest/meta-data/",
	"/latest/user-data/",
	"/latest/dynamic/",
	"/metadata/v1/",
	"/metadata/v1/maintenance",
	"/computeMetadata/v1/",
	"/computeMetadata/v1/project/",
	"/metadata/instance",
	"/config/getuser",

	// ── 국정원 점검 관련 (한국 웹 특화) ──
	"/member/join",
	"/member/login",
	"/member/info",
	"/member/modify",
	"/member/delete",
	"/member/find_id",
	"/member/find_pw",
	"/member/cert",
	"/board",
	"/board/",
	"/board/list",
	"/board/view",
	"/board/write",
	"/board/modify",
	"/board/delete",
	"/board/reply",
	"/board/download",
	"/bbs",
	"/bbs/",
	"/bbs/board.php",
	"/bbs/login.php",
	"/bbs/register.php",
	"/notice",
	"/notice/",
	"/notice/list",
	"/faq",
	"/faq/",
	"/qna",
	"/qna/",
	"/qna/write",
	"/community",
	"/freeboard",
	"/gallery",
	"/photo",
	"/download",
	"/download/",
	"/file_download",
	"/fileDownload",
	"/common/download",
	"/common/file",
	"/cmm/fms/FileDown.do",
	"/cop/bbs/selectBoardList.do",
	"/search",
	"/search/",
	"/sitemap",
	"/intro",
	"/main",
	"/main/",
	"/sub",
	"/content/view",
	"/contents",
	"/page",
	"/index.action",
	"/index.do",
	"/index.jsp",
	"/index.asp",
	"/index.aspx",
	"/index.html",
	"/index.htm",
	"/index.php",
	"/default.asp",
	"/default.aspx",
	"/default.htm",
	"/home.do",
	"/home.action",
	"/error/error.jsp",
	"/error/error.asp",
	"/error/error.do",
	"/common/error",
	"/uat/uia/egovLoginUsr.do",
	"/uat/uia/actionLogin.do",
	"/uss/umt/EgovMberManageAPI.do",
	"/sym/log/SelectSysLogList.do",
	"/sec/ram/EgovAuthorList.do",
}

func BruteforceDirectories(ctx context.Context, baseURL string, client scanner.HttpClient, threads int) []DiscoveredPath {
	if ctx == nil || client == nil {
		return nil
	}

	trimmedBaseURL := strings.TrimSpace(baseURL)
	if trimmedBaseURL == "" {
		return nil
	}

	if threads < 1 {
		threads = 1
	}

	trimmedBaseURL = strings.TrimRight(trimmedBaseURL, "/")

	results := make([]DiscoveredPath, 0, len(commonPaths))
	var mu sync.Mutex
	var wg sync.WaitGroup

	sem := make(chan struct{}, threads)

launchLoop:
	for _, path := range commonPaths {
		if ctx.Err() != nil {
			break
		}

		select {
		case sem <- struct{}{}:
			wg.Add(1)
			go func(path string) {
				defer wg.Done()
				defer func() { <-sem }()

				if ctx.Err() != nil {
					return
				}

				url := trimmedBaseURL + path
				req := &scanner.Request{
					Method: "GET",
					URL:    url,
				}

				resp, err := client.Do(ctx, req)
				if err != nil || resp == nil {
					return
				}

				size := len(resp.Body)
				if resp.StatusCode == 404 || size == 0 {
					return
				}

				if isSoft404(resp.StatusCode, resp.Body, size) {
					return
				}

				mu.Lock()
				results = append(results, DiscoveredPath{
					URL:        url,
					StatusCode: resp.StatusCode,
					Size:       size,
				})
				mu.Unlock()
			}(path)
		case <-ctx.Done():
			break launchLoop
		}
	}

	wg.Wait()

	sort.Slice(results, func(i, j int) bool {
		if results[i].StatusCode == results[j].StatusCode {
			return results[i].URL < results[j].URL
		}
		return results[i].StatusCode < results[j].StatusCode
	})

	return results
}

func isSoft404(statusCode int, body string, size int) bool {
	if statusCode != 200 || size >= 2000 || size == 0 {
		return false
	}

	lower := strings.ToLower(body)
	soft404Phrases := []string{
		"page not found",
		"the page you requested was not found",
		"this page could not be found",
		"404 error",
		"404 -",
		"error 404",
		"does not exist",
	}

	for _, phrase := range soft404Phrases {
		if strings.Contains(lower, phrase) {
			return true
		}
	}

	return false
}
