// Package rules manages detection rules generated by the evolution engine.
// Rules are stored as JSON files (one per rule) in a rules directory.
package rules

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Rule represents a detection rule generated from CVE data or LLM analysis.
type Rule struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	CVEID       string        `json:"cve_id,omitempty"`
	CWE         []string      `json:"cwe,omitempty"`
	Severity    string        `json:"severity"`
	Tags        []string      `json:"tags,omitempty"`
	Requests    []RuleRequest `json:"requests"`
	Matchers    []Matcher     `json:"matchers"`
	Enabled     bool          `json:"enabled"`
	Source      string        `json:"source"` // "cve-ingester", "llm-generated", "manual"
	Generated   time.Time     `json:"generated"`
	LastUpdated time.Time     `json:"last_updated"`
}

// RuleRequest defines an HTTP request to send during detection.
type RuleRequest struct {
	Method  string            `json:"method"`
	Path    string            `json:"path"`
	Headers map[string]string `json:"headers,omitempty"`
	Body    string            `json:"body,omitempty"`
	// Payloads is a list of payload strings to inject.
	// Each payload generates a separate request.
	Payloads []string `json:"payloads,omitempty"`
	// InjectIn specifies where to inject the payload: "path", "query", "body", "header"
	InjectIn string `json:"inject_in,omitempty"`
}

// Matcher defines how to determine if a response indicates a vulnerability.
type Matcher struct {
	Type      string   `json:"type"` // "status", "body", "header", "regex", "time"
	Values    []string `json:"values,omitempty"`
	Part      string   `json:"part,omitempty"`      // "body", "header", "status"
	Condition string   `json:"condition,omitempty"` // "and", "or" (default: "or")
	Negative  bool     `json:"negative,omitempty"`  // match if NOT found
}

// Store manages rules on disk.
type Store struct {
	dir   string
	rules map[string]*Rule
}

// NewStore creates a rule store at the given directory.
func NewStore(dir string) (*Store, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, fmt.Errorf("creating rules dir: %w", err)
	}
	s := &Store{
		dir:   dir,
		rules: make(map[string]*Rule),
	}
	if err := s.loadAll(); err != nil {
		return nil, err
	}
	return s, nil
}

// Save writes a rule to disk.
func (s *Store) Save(rule *Rule) error {
	rule.LastUpdated = time.Now()
	s.rules[rule.ID] = rule

	filename := sanitizeFilename(rule.ID) + ".json"
	path := filepath.Join(s.dir, filename)

	data, err := json.MarshalIndent(rule, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling rule %s: %w", rule.ID, err)
	}

	return os.WriteFile(path, data, 0o644)
}

// Get returns a rule by ID.
func (s *Store) Get(id string) (*Rule, bool) {
	r, ok := s.rules[id]
	return r, ok
}

// All returns all loaded rules.
func (s *Store) All() []*Rule {
	result := make([]*Rule, 0, len(s.rules))
	for _, r := range s.rules {
		result = append(result, r)
	}
	return result
}

// Enabled returns only enabled rules.
func (s *Store) Enabled() []*Rule {
	var result []*Rule
	for _, r := range s.rules {
		if r.Enabled {
			result = append(result, r)
		}
	}
	return result
}

// Count returns the total number of rules.
func (s *Store) Count() int {
	return len(s.rules)
}

// Delete removes a rule from disk and memory.
func (s *Store) Delete(id string) error {
	delete(s.rules, id)
	filename := sanitizeFilename(id) + ".json"
	path := filepath.Join(s.dir, filename)
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("deleting rule file: %w", err)
	}
	return nil
}

// loadAll reads all rule files from the directory.
func (s *Store) loadAll() error {
	entries, err := os.ReadDir(s.dir)
	if err != nil {
		return fmt.Errorf("reading rules dir: %w", err)
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}

		path := filepath.Join(s.dir, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			continue // skip unreadable files
		}

		var rule Rule
		if err := json.Unmarshal(data, &rule); err != nil {
			continue // skip malformed files
		}

		s.rules[rule.ID] = &rule
	}

	return nil
}

// sanitizeFilename makes a string safe for use as a filename.
func sanitizeFilename(s string) string {
	replacer := strings.NewReplacer(
		"/", "_",
		"\\", "_",
		":", "_",
		"*", "_",
		"?", "_",
		"\"", "_",
		"<", "_",
		">", "_",
		"|", "_",
		" ", "-",
	)
	return replacer.Replace(s)
}
